/*
 * program.c
 *
 *  Created on: Jul 30, 2024
 *      Author: shimaa
 */

//includes
#include "C:\Users\shimaa\Documents\projectEM\LIB\STD_TYPE.h"
#include"interface.h"
#include"config.h"
#include "C:\Users\shimaa\Desktop\microwave_project\code\slave\MCAL\DIO\interface.h"
//implementation

void KEYPAD_H_INIT()
{
	u8 ROW_INDEX= KEY_PAD_row_0;
	u8 COL_INDEX= KEY_PAD_column_0;


	for(ROW_INDEX=KEY_PAD_row_0;ROW_INDEX<=KEY_PAD_row_3;ROW_INDEX++){
DIO_M_SET_PIN_DIRECTION(KETPAD_PORT,ROW_INDEX,OUTPUT);
DIO_M_SET_PIN_VALUE(KETPAD_PORT,ROW_INDEX,HIGH);//pull_up fun

	}

	for(COL_INDEX=KEY_PAD_column_0;COL_INDEX<=KEY_PAD_column_3;COL_INDEX++){
	DIO_M_SET_PIN_DIRECTION(KETPAD_PORT,COL_INDEX,INPUT);
	DIO_M_SET_PIN_VALUE(KETPAD_PORT,COL_INDEX,HIGH);//pull_up fun
	}
}

void KEYPAD_H_GET_BUTTON(u8 *U8CHAR)
{
u8 LOCAL_KEYPAD_ARR[KET_PAD_ROW_NUM][KET_PAD_COLUMN_NUM]= KEYPAD_ARR;
u8 LOCAL_COLUMN_INDEX =0,LOCAL_ROW_INDEX=0;
u8 LOCAL_COLUMN_ARR[KET_PAD_COLUMN_NUM]={KEY_PAD_column_0,KEY_PAD_column_1,KEY_PAD_column_2,KEY_PAD_column_3};
u8 LOCAL_ROW_ARR[KET_PAD_ROW_NUM]={KEY_PAD_row_0,KEY_PAD_row_1,KEY_PAD_row_2,KEY_PAD_row_3};
u8 LOCAL_STATE=1;

for(LOCAL_ROW_INDEX=0;LOCAL_ROW_INDEX<KET_PAD_ROW_NUM;LOCAL_ROW_INDEX++){
	DIO_M_SET_PIN_VALUE(KETPAD_PORT,LOCAL_ROW_ARR[LOCAL_ROW_INDEX],LOW);
	for(LOCAL_COLUMN_INDEX=0;LOCAL_COLUMN_INDEX<KET_PAD_COLUMN_NUM;LOCAL_COLUMN_INDEX++){
		DIO_M_GET_PIN_VALUE(KETPAD_PORT,LOCAL_COLUMN_ARR[LOCAL_COLUMN_INDEX],&LOCAL_STATE);
		if(LOCAL_STATE==KEY_PAD_pressed){
			while(LOCAL_STATE==KEY_PAD_pressed){
				DIO_M_GET_PIN_VALUE(KETPAD_PORT,LOCAL_COLUMN_ARR[LOCAL_COLUMN_INDEX],&LOCAL_STATE);
			}
			*U8CHAR=LOCAL_KEYPAD_ARR[LOCAL_ROW_INDEX][LOCAL_COLUMN_INDEX];
		}
	}
	DIO_M_SET_PIN_VALUE(KETPAD_PORT,LOCAL_ROW_ARR[LOCAL_ROW_INDEX],HIGH);
}
}
